  version : 0.1
 phases :
   install :
     commands :
       - " touch .npmignore "
       - " npm install -g gatsby "
   pre_build :
     commands :
       - " npm install "
   build :
     commands :
       - " npm run build "
   post_build :
     commands :
       - ' aws s3 sync "public/" "https://s3.console.aws.amazon.com/s3/buckets/miika-rgf-ghost/" --delete --acl "public-read" && aws cloudfront create-invalidation --distribution-id DISTRIBUTION_ID --paths "/*" '
 artifacts :
   base-directory : public
   files :
     - " **/* "
   discard-paths : yes
 cache :
   paths :
     - " .cache/* "
     - " node_modules/* "
     - " public/* " 